# Generated by Django 3.2.9 on 2021-12-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('vote', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.position'),
        ),
        migrations.AlterField(
            model_name='eligibleid',
            name='CIN',
            field=models.FloatField(null=True),
        ),
    ]
