# Generated by Django 3.2.9 on 2021-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_candidate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
