# Generated by Django 3.2.9 on 2021-12-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_candidate_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingprocess',
            old_name='date',
            new_name='date_voting',
        ),
        migrations.RenameField(
            model_name='votingprocess',
            old_name='vote',
            new_name='voting_process',
        ),
    ]
