# Generated by Django 3.2.9 on 2021-12-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20211208_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibleid',
            name='voting_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.position'),
        ),
    ]
