# Generated by Django 3.2.9 on 2021-12-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_eligibleid_voting_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibleid',
            name='voting_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.votingprocess'),
        ),
    ]
