# Generated by Django 3.2.9 on 2021-12-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_eligibleid_voting_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingprocess',
            name='voting_process',
            field=models.BooleanField(default=False),
        ),
    ]
