# Generated by Django 3.2.9 on 2021-12-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_rename_position_position_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pname',
            new_name='position_name',
        ),
    ]
