# Generated by Django 3.2.9 on 2021-12-09 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0014_eligibleid_eligible_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VotingProcess',
            new_name='Voting',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='voting_process',
            new_name='voter_has_voted',
        ),
        migrations.AlterField(
            model_name='eligibleid',
            name='eligible_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligibleid',
            name='voting_process',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.voting'),
        ),
    ]
