# Generated by Django 3.2.9 on 2021-12-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_auto_20211209_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='number',
            new_name='candidate_number',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='votes',
            new_name='votes_counter',
        ),
        migrations.RenameField(
            model_name='eligibleid',
            old_name='CIN',
            new_name='cin',
        ),
        migrations.RenameField(
            model_name='eligibleid',
            old_name='voting_process',
            new_name='voting',
        ),
    ]
