# Generated by Django 3.2.9 on 2021-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_alter_candidate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibleid',
            name='voting',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='voter_has_voted',
        ),
        migrations.AddField(
            model_name='eligibleid',
            name='voter_has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
