# Generated by Django 3.2.9 on 2021-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0018_auto_20211213_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting',
        ),
        migrations.AddField(
            model_name='eligibleid',
            name='date_voting',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
