# Generated by Django 3.2.9 on 2021-12-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0021_alter_eligibleid_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_vote', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.candidate')),
            ],
        ),
    ]
