# Generated by Django 3.2.9 on 2021-12-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0022_auto_20211216_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='eligibleId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vote.eligibleid'),
        ),
    ]
